### ISSUE TITLE
Does this work with Webpack's HMR

### ISSUE THREAD

**Issue by pruett** [css-modules/webpack-demo#10]
Great starter repo. I really love CSS Modules! Curious if this works with Wepack's HMR. I'm not able to get it to work. Thanks again!

**Comment by alopes** [comment]
@pruett, did you manage to get it working?

**Comment by pruett** [comment]
@alopes yes! i'm using https://github.com/gaearon/react-transform-boilerplate and implementing css-modules on top of it.

**Comment by MattSPalmer** [comment]
Hey @pruett, can you point to a public repo of yours that has a working example of this? I'm using something close to react-transform-boilerplate, but still having issues.

Given a component file that starts with the following:

``` js
import React from 'react';
import styles from '../../less/main.less';
```

Webpack tells me it can't hot update main.less. Is this similar to the trouble you were having initially?

**Comment by pruett** [comment]
Hm. Not by a computer at the moment but I'll try and reproduce an example in a public repo and show you my setup. I wasn't using a css preprocessor, just plain css modules although I don't see why that would be a problem if you chain a less loader to the process.

**Comment by MattSPalmer** [comment]
Sure thing, config is below.

``` js
var path = require('path');
var webpack = require('webpack');
var ExtractTextPlugin = require('extract-text-webpack-plugin');

var entries = ['./src/main'];

var output = {
  filename: 'bundle.min.js',
  path: path.join(__dirname, 'dist/'),
  publicPath: '/'
};

var styleLoader = {
  test: /\.less$/,
  loaders: [
    "style-loader",
    "css?modules",
    "less"
  ]
  // loader: 'style!css!less'
};

var postcss = [
  require('autoprefixer')({browsers: ['last 2 versions']})
];

var development = {
  // Create Sourcemaps for the bundle
  devtool: 'source-map',

  entry: [
        'webpack/hot/dev-server',
        'webpack-hot-middleware/client'
    ].concat(entries),

  output: output,

  plugins: [
    new webpack.optimize.OccurenceOrderPlugin(),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.optimize.DedupePlugin(),
    new webpack.NoErrorsPlugin()
  ],

  module: {
    loaders: [
      {
        test: path.join(__dirname, '/src/js'),
        loaders: ['babel']
      },
      styleLoader
    ],
    postcss: postcss
  },
  stats: {
    errorDetails: true
  }
};

// ... removed for brevity ...

module.exports = {
  build: build,
  development: development
};
```

**Comment by pruett** [comment]
@alopes @MattSPalmer here's a commit on top of the boilerplate that allows hot reloading css module functionality. let me know if this helps at all. https://github.com/pruett/react-transform-boilerplate/commit/2d14fd242d6ed26bba898a821f9ede2aa1cbc313

**Comment by MattSPalmer** [comment]
That helped me zero on in on my issue, thanks! Turns out I was requiring `main.less` in both my webpack entry file and the component using the style, and it was making HMR unhappy. 

Everything is now working as expected, including the less loader further up the preprocessing chain.

**Comment by pruett** [comment]
:+1:
