### ISSUE TITLE
source maps?

### ISSUE THREAD

**Issue by lifeiscontent** [css-modules/webpack-demo#12]
Are there source maps that get generated in this project? That's the one thing that is making me hesitant to switch.

**Comment by patrikholcak** [comment]
Hey @lifeiscontent,

you can enable source maps for both js and css in your [webpack config](https://webpack.github.io/docs/configuration.html#devtool) via the `devtool` property. If you also want to enable css source maps, just add a query parameter `sourceMap` to `css-loader`. So it looks something like this `css-loader?sourceMap`. Hope it helps!
