### ISSUE TITLE
Question about using with sass loader

### ISSUE THREAD

**Issue by anthony-dandrea** [css-modules/webpack-demo#13]
Is there a clean way to use this in tandem with Sass-Loader? I would like to use my mixins and variables but still keep my classes namespaced locally.

**Comment by patrikholcak** [comment]
Shouldn’t be a problem. Just replace `postcss-loader` with your sass loader.

**Comment by patrikholcak** [comment]
Hey @anthony-dandrea did you have any problems with the sass-loader? Please close the issue if the problem is resolved :)

**Comment by anthony-dandrea** [comment]
Haven't actually been able to try it yet but I'll close it for now. If it doesn't work I'll let you know. Thank you.

**Comment by anthony-dandrea** [comment]
This worked great btw. Ty!

**Comment by patrikholcak** [comment]
Cool! Let me know if you need any more help
