### ISSUE TITLE
Explaining the modules

### ISSUE THREAD

**Issue by verpixelt** [css-modules/webpack-demo#18]
For a beginner the amount of modules this demo requires might be overwhelming without a proper explanation. I myself had to go through each of them and look them up to get a rough idea what exactly I need to run CSS Modules with webpack.
A short explanation in the Readme how they work together might be helpful to get people started more easily.
I would do it myself but I still haven't grasped the whole thing.

**Comment by nilshartmann** [comment]
I stumbled across the same problem and tried to understand what each module means. Here's what I've found so far. Please correct me where I'm wrong.

## Modules required for CSS modules

| Module | Description |
| --- | --- |
| [webpack](https://webpack.github.io/) | Webpack (obviously...) |
| [webpack-dev-server](https://webpack.github.io/docs/webpack-dev-server.html) | (Optional) Supports hotloading of changed files etc while developing |
| [style-loader](https://github.com/webpack/style-loader) and [css-loader](https://github.com/webpack/css-loader) | `style-loader` and `css-loader` process your CSS files. `css-loader` is the loader that actual makes [CSS modules work](https://github.com/webpack/css-loader#css-modules). |

For me it was enough to include the above modules and then configuring the following loader for CSS files in my `webpack.config.js` file:

```
. . .
{
  test: /\.css$/,
  loader: 'style!css-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]' 
}
. . .
```

## Optional modules

The following modules control the **actual CSS processing**. They are not CSS modules specific and can be used with both "regular" CSS and CSS modules: 

| Module | Description |
| --- | --- |
| [postcss-loader](https://github.com/postcss/postcss-loader) | Allows execution of various CSS post processor in Webpack. Required for `autoprefixer-core` and `postcss-color-rebeccapurple` |
| [autoprefixer-core](https://github.com/ai/autoprefixer-core) | Add vendor-prefixes to your css code (according to the GitHub page it is deprecated and should be replaced by [autoprefixer](https://github.com/postcss/autoprefixer) |
| [postcss-color-rebeccapurple](https://github.com/postcss/postcss-color-rebeccapurple) | Another CSS post processor. Only needed to support `rebeccapurple` color in CSS |

|[extract-text-webpack-plugin](https://github.com/webpack/extract-text-webpack-plugin)|Writes the CSS code processed by Webpack into an own CSS-file and not into the generated bundle JavaScript file.|

## Unrelated modules

This modules are just for the demo application:

| Module | Description |
| --- | --- |
| [babel-*](https://babeljs.io) | ESx-to-ES5 compiler. Mostly needed for React code |
| ejs |  |
| react-to-html-webpack-plugin |  |
| [node-libs-browser](https://github.com/webpack/node-libs-browser) |  |
| gh-pages |  |
| [url-loader](https://github.com/webpack/url-loader) | Webpack file handling, e.g. for images |
| [file-loader](https://github.com/webpack/file-loader) | Webpack file handling, e.g. for images |
| [raw-loader](https://github.com/webpack/raw-loader) | It’s used to load raw css files (as utf8) into the demo so it can be rendered into `<code>` |

**Comment by patrikholcak** [comment]
`raw-loader` is also unrelated to css modules. It’s used to load raw css files (as utf8) into the demo so it can be rendered into `<code>`

`postcss-color-rebeccapurple`… I honestly don’t know why on earth is it here. It just confuses people.

**Comment by nilshartmann** [comment]
@patrikholcak Thanks for your comment, I've changed the table. 

BTW I think it could be helpful to have a "CSS modules starter edition" of this demo containing only the required modules and Webpack features (maybe on it's own branch)

**Comment by patrikholcak** [comment]
It definitely would be helpful. But I don’t see it happening here as no one is really maintaining this repository. I got so frustrated by the situation that I created a react css-modules [starterpack](https://github.com/patrikholcak/css-modules-starterpack) (with hot reload, babel,…). It’s not suitable for everyone and not the best by any means but it’s a solid starter pack if you take css modules seriously.

**Comment by joshwnj** [comment]
@nilshartmann that's a great summary of modules - I encourage you to submit it as a PR to README.md

@patrikholcak it would be great to put a link to your starterpack on the readme too, as I think a lot of people coming to this repo would benefit from seeing it

**Comment by patrikholcak** [comment]
Yes, submitting a PR is the best way to get something merged. …assuming there’s someone who maintains this repo and eventually merges it.

@joshwnj Thanks for nominating me but I’d much rather see this repo being updated, with a good readme, examples, solid support and no `postcss-color-rebeccapurple` (I’m sorry but, I’ll bring this module in every argument, because of how ridiculous it is).

I understand this is a demo repo — not a starterpack, but it doesn’t “sell” the technology well. Not to me and not in this state.

**Comment by joshwnj** [comment]
@patrikholcak I can understand that the decisions made here are not to your taste, and that's fair enough. But that is what the `Fork` button is for :)

If you don't want to submit a PR that's fine too.

**Comment by nilshartmann** [comment]
Thanks fo your feedback, @joshwnj - I'll send you a PR for the README later today
