### ISSUE TITLE
Demo out of date?

### ISSUE THREAD

**Issue by mikeaustin** [css-modules/webpack-demo#36]
Last updated 2 years ago. I'm unsuccessfully trying to add css-modules to a simple project.

ERROR in ./src/client/app/index.jsx
Module not found: Error: Can't resolve 'style' in '/Library/WebServer/Documents/www.mike-austin.com/models'
BREAKING CHANGE: It's no longer allowed to omit the '-loader' suffix when using loaders.
                 You need to specify 'style-loader' instead of 'style',
                 see https://webpack.js.org/guides/migrating/#automatic-loader-module-name-extension-removed
 @ ./src/client/app/index.jsx 13:14-37

**Comment by arkilis** [comment]
The tutorial is out of date already.

**Comment by mojoaxel** [comment]
Needs to be updated to Webpack 3.
